package com.swp_group4.back_end.enums;

public enum ConstructionOrderStatus {

    REQUESTED, CONSULTING, QUOTATION, CONFIRMED_QUOTATION, DESIGNING,
    DESIGNED, CONFIRM_DESIGN, CONSTRUCTING, CONSTRUCTED, FINISHED, CANCELLED, NULL;

}
